Vagrant.configure("2") do |config|

  config.vm.define "rocky" do |rocky|
    rocky.vm.box = "rockylinux/8"
    
    rocky.vm.synced_folder "salt/roots/", "/srv/salt/"
    rocky.vm.synced_folder "{{cookiecutter.name}}", "/srv/salt/formulas/{{cookiecutter.name}}"
    rocky.vm.synced_folder "salt/pillar/", "/srv/pillar/"
    
    rocky.vm.network "private_network", type: "dhcp"
    
    ## Use all the defaults:
    rocky.vm.provision :salt do |salt|
      salt.masterless = true
      salt.minion_config = "salt/minion"
      salt.run_highstate = true

    end
  end

  config.vm.define "debian" do |debian|
    debian.vm.box = "debian/contrib-buster64"
    
    debian.vm.synced_folder "salt/roots/", "/srv/salt/"
    debian.vm.synced_folder "{{cookiecutter.name}}", "/srv/salt/formulas/{{cookiecutter.name}}"
    debian.vm.synced_folder "salt/pillar/", "/srv/pillar/"
    
    debian.vm.network "private_network", type: "dhcp"
    
    ## Use all the defaults:
    debian.vm.provision :salt do |salt|
      salt.masterless = true
      salt.minion_config = "salt/minion"
      salt.run_highstate = true

    end
  end

end
